# Generated by Django 4.2.1 on 2025-03-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientunits',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_units', to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientunits',
            name='unit',
            field=models.ForeignKey(db_column='unit', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_units', to='recipes.unit'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(db_column='unit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.unit'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
        ),
    ]
