# Generated by Django 4.2.1 on 2025-03-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredientunits_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories_per_100',
            field=models.FloatField(default=0),
        ),
    ]
