# Generated by Django 4.2.1 on 2025-03-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_calories_per_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_min',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
