# Generated by Django 4.2.1 on 2025-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_is_public_alter_recipe_main_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbs_per_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats_per_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins_per_100',
            field=models.FloatField(default=0),
        ),
    ]
